# Generated by Django 3.0.7 on 2020-07-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsimage',
            table='df_goods_image',
        ),
    ]
