# Generated by Django 3.0.7 on 2020-07-30 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
        ('user', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=128)),
                ('pay_method', models.SmallIntegerField(choices=[(0, '货到付款'), (1, '微信支付'), (2, '支付宝'), (3, '银联支付')], default=2)),
                ('total_count', models.IntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order_status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成')], default=0)),
                ('trade_no', models.CharField(max_length=256)),
                ('address', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='user.Address')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OrderInfo',
                'verbose_name_plural': 'OrderInfos',
                'db_table': 'df_order_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.CharField(max_length=256)),
                ('goods_sku', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKU')),
                ('order_info', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.OrderInfo')),
            ],
            options={
                'verbose_name': 'OrderGoods',
                'verbose_name_plural': 'OrderGoodses',
                'db_table': 'df_order_goods',
                'managed': True,
            },
        ),
    ]
